"""empty message

Revision ID: 7e3d32b10fb8
Revises: 85f81108926b
Create Date: 2022-10-24 20:03:50.660093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e3d32b10fb8'
down_revision = '85f81108926b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('start_time', sa.DateTime(), nullable=False))
    op.add_column('Show', sa.Column('start_time', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Show', 'start_time')
    op.drop_column('Artist', 'start_time')
    # ### end Alembic commands ###
